version: '3'
services:
  apatch:
    image: httpd
    ports:
      - 9200:80
    networks: [docker-java]
  tomcat:
    image: tomcat
    networks: [docker-java]
    ports:
      - 8009:8080 
networks:
  docker-java:
