version: '3'
services:
  apatch:
    image: httpd
    ports:
      - 9200:80
    networks: [docker-java]
  tomcat:
    image: tomcat
    networks: [docker-java]
    ports:
      - 8009:8080
    volumes:
      - './app/sample.war:/usr/local/tomcat/webapps/sample.war'
      - './app/setenv.sh:/usr/local/tomcat/bin/setenv.sh'
networks:
  docker-java:
